### ISSUE TITLE
Using sensor with UART

### ISSUE THREAD

**Issue by fetchinson** [sparkfun/SparkFun_ZX_Distance_and_Gesture_Sensor_Arduino_Library#3]
I'm trying to understand the data leaving the sensor when read out via UART. The Z and X data is clear, but I'm not sure what the two numbers following ZX_UART_RANGES parsed in between lines 67 and 73 of [UART_ZX_Demo.ino](https://github.com/sparkfun/SparkFun_ZX_Distance_and_Gesture_Sensor_Arduino_Library/blob/master/examples/UART_ZX_Demo/UART_ZX_Demo.ino) are. What do these two numbers stand for?

**Comment by andawna** [comment]
These numbers are the raw energies collected by the IR receiver from the IR emitter operating at the moment. They are sometimes called the pseudo-ranges, but these numbers get larger as the reflector gets closer to the sensor so they are more a measure of reflected energy. They are used to calculate the Z and X coordinates. Does that help?

**Comment by fetchinson** [comment]
Yes! Thanks a lot, all clear now, since I have the Z and X values I can just ignore this pair of numbers then.

**Comment by ShawnHymel** [comment]
Sweet, thanks @andawna!
