### ISSUE TITLE
Gestures on UART

### ISSUE THREAD

**Issue by blundell** [sparkfun/SparkFun_ZX_Distance_and_Gesture_Sensor_Arduino_Library#4]
Hi, I see in this commit from two years ago Gestures weren't supported on UART

https://github.com/sparkfun/SparkFun_ZX_Distance_and_Gesture_Sensor_Arduino_Library/commit/42ce5b419fa6b5502bcaf1e077986e0dc3af6241

it says a firmware update was needed. Is this still a problem on the latest shipping sensor?

(i..e has it been fixed in the last two years... :-) )

![UART gestures not supported](https://user-images.githubusercontent.com/655860/27768397-71f438be-5f0a-11e7-9f2f-b6bbc3aaa558.jpeg)

**Comment by ADataDate** [comment]
I want to say yes - but I will be back in the office on Wednesday where I can run some tests and confirm that. I'll let you know as soon as I do.

**Comment by blundell** [comment]
thats cool, its Wednesday now in my timezone, any luck? :-)

**Comment by ADataDate** [comment]
I've had no issue using this demo with the new sensor. Seems fully supported. Ran 100 tests with about 85% accuracy on "up swipe". Left and right had no issues at all.  My test set-up leaves something to be desired though as I was holding the sensor in one hand and gesturing with the other. If you have any more questions let us know.

**Comment by blundell** [comment]
Thanks! Confirmed working from my side as well UART on AndroidThings: https://github.com/blundell/androidthings-uart/blob/master/app/src/main/java/com/blundell/tut/MainActivity.java
