### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by blundell** [sparkfun/SparkFun_ZX_Distance_and_Gesture_Sensor_Arduino_Library#5]
At the bottom of the datasheet here: https://cdn.sparkfun.com/assets/learn_tutorials/3/4/5/XYZ_Interactive_Technologies_-_ZX_SparkFun_Sensor_Datasheet.pdf

it says

> "Note that this is a high level description of the data available for the I2C protocol. More details of the ZX sensor I2C specification may be obtained from the GestureSense ZX Sensor I2C Register Map spreadsheet. This spreadsheet is available for advanced I2C users and may be consulted for programming the I2C interface requiring the details of the pin assignments including the DR pin."

Could you point me to the location of the 'register map' spreadsheet please?

**Comment by ADataDate** [comment]
https://www.sparkfun.com/products/13162, scroll down to the "Documents" section, its called "XYZ I2C Register Map.

**Comment by blundell** [comment]
💯
